# Site settings
title: Excellence at Scale, a blog by Jesse Williams
description: "A simple blog focused on the complexity operational excellence, with a focus on startups, messaging, and positioning."
url: "http://jesse-williams.com"
author:
  name: "Jesse Williams"
  email: "jessewilliams.r@gmail.com"
logo: /img/jesse-williams-logo.png

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      

# Custom variables
version: "1.2.0"

# Build settings
theme: minima



# Options
custom_header: false
custom_nav_footer: false
reverse: false


